language: node_js
node_js:
- 12
env:
  global:
    secure: ibrr9Js9d7yYybif6IIug2ohpCCBLYt7waYN/yI99vfSxd6R0Y83MzHkI505tPue8U1PyvMg3r2LxJ3gmOUem5UpqQPqMCVa9Ck1FfXTK6NtRXN7caK/Q+Rd5CTOPTAKj8JB+QcZQoBpDq/xUNEhUIUldn8KVDqqFvV4sEk1zK9eeHXMXQjmqdKoGLEnxspU5WN7072tqZdUr4r8/m4E+s2o9r92Ya0Jck4J1MmWM6YBpEatEwA56wyeY8iDvLIyuYWKF5VsixAhVG8tIlMlXj+6iZywz7WhnX3x/RerKWNBAocRppQLaKFhydotQukBMzbgAdlgEQ3Dvk9J38HhrUmViTgwH/0aX9CQu5bLZMam0sk1HIeEdns1LrJeTyMIjGoJnC1ZQLGTYPc0igk/MDGVAcjdzJKTdletynlhKaieD5b2GpVhW/vXOrPKQlmfMcPeAYxIHkMmP+H/OHETR+rkD0etgcOKcULGzuInNLskGndHSscSzhSnkgNzTpeEp/dPODjo78ele+nFfhZ7PL0sZucBrXu6LrqjLirAaScKoirZ7Hb3C2WJMQQIOX1HwsA/ObKBxpMxCPREYArYjs69v+PPiEWpTIqosvbvBTMR7m2C1WtCDnNONpfLCRjR3qEOiyVQ2q5gXNCQIio42hhFba17/NzxBjylaJk419k=
before_script:
- git config --global user.email "basaratali@gmail.com"
- git config --global user.name "Travis-CI"
- git remote set-url origin https://github.com/basarat/byots.git
script:
- bash prepare.sh
after_success:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git config --global push.default matching
- bash release.sh
branches:
  only:
  - master
deploy:
  skip_cleanup: true
  provider: npm
  email: basaratali@gmail.com
  api_key: "$NPM_TOKEN"
  on:
    repo: basarat/byots
